config/urls.py
from django.contrib import admin
from django.urls import include, path
from . import settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('dashboard/', include('dashboard.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/urls.py
from django.urls import path

from . import views

app_name = 'dashboard'
urlpatterns = [
#    path('', views.MainView.dashboard_view, name='main'),
  path('', views.MainView.datatable_view, name='main'),
#    path('', views.MainView.myapp_list_view, name='main'),
  path('dashboard2/', views.Dash2_view, name='dashboard2'),
  path('dashboard3/', views.Dash3_view, name='dashboard3'),

]

dashboard/models.py
from django.db import models


class Timestamp(models.Model):
  created = models.DateTimeField(auto_now_add=True)
  modified = models.DateTimeField(auto_now=True)
  class Meta:
    abstract =True

class DailyReport(Timestamp):
    # 一応名前を入れておく
    name = models.CharField(max_length=100)
    # 業務内容
    daily_description = models.CharField(max_length=255)
    # wowポイント
    wow_point = models.CharField(max_length=255)
    # 成長の種
    seeds_of_growth = models.CharField(max_length=255)

    def __str__(self):
      return self.name

dashboard/views.py
from django.shortcuts import render
from django.views.generic import ListView
import io
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import base64




class MainView:
    
    # 棒グラフを出したい時
    # def dashboard_view(request): # ViewFunctionと呼ぶ
    #    chart_label = ['レッド', 'Blue', 'Yellow', 'Green', 'Purple', 'Orange']
    #    chart_data = [1, 5, 1, 0, 0, 0]
    #    context = {'chart_data': chart_data, 'chart_label': chart_label}
    #    return render(request,template_name,context)
    
    # datatableを出したい時
    def datatable_view(request): # ViewFunctionと呼ぶ
        template_name = "main.html"
        ctx = {}
        ctx["object_list"] = [{'id':1, 'name':'北海道'},{'id':2, 'name':'青森県'},{'id':3, 'name':'岩手県'}]
        return render(request, template_name, ctx)

    # リストが機能しているか見たい時
    # def myapp_list_view(request):
    #     ctx = {}
    #     ctx["object_list"] = ["python", "javascript", "html", "css"]
    #     ctx["object_tuple"] = ("python", "javascript", "html", "css")
    #     ctx["object_dict"] = {"P": "python", "J": "javascript", "H": "html", "C": "css"}
    #     ctx["object_empty"] = []
    #     return render(request, template_name, ctx)

# class Dash2View(ListView):
#     template_name = "dashboard2.html"

# class Dash3View(ListView):
#     template_name = "dashboard3.html"

def Dash2_view(request):
    chart_label = ['Red', 'Blue', 'Yellow', 'Green', 'Purple', 'Orange']
    chart_data = [1, 5, 1, 0, 0, 0]
    context = {'chart_data': chart_data, 'chart_label': chart_label}
    return render(request, "dashboard2.html",context)


def create_graph(x_list,t_list):
    plt.cla()
    plt.plot(t_list, x_list, label="x")
    plt.xlabel('t')
    plt.ylabel('x')

def get_image():
    buffer = io.BytesIO()
    plt.savefig(buffer, format='png')
    image_png = buffer.getvalue()
    graph = base64.b64encode(image_png)
    graph = graph.decode('utf-8')
    buffer.close()
    return graph

def Dash3_view(request):
    x_list = [3, 6, 12, 24, 48, 96, 192, 384, 768, 1536, 3072]
    t_list = [1,2,3,4,5,6,7,8,9,10,11]
    create_graph(x_list, t_list)
    graph = get_image()
    return render(request, "dashboard3.html", {'graph': graph})

dashboard/templates/_main_footer.html
  <!-- Main Footer -->
  <footer class="main-footer">
    <!-- To the right -->
        <div class="float-right d-none d-sm-block">
        {% block footer_right %}
            <b>Version</b> {% block version %}0.1{% endblock %}
        {% endblock %}
    </div>

    {% block footer_left %}
    {% block legal %}
    <strong>Copyright &copy; {% now "Y" %}{% if not site %}.{% endif %}
        {% if site %}
            <a href="http://{{ site.domain }}">{{ site.name }}</a>
        {% endif %}
    </strong> All rights
    reserved.
    {% endblock %}
    {% endblock %}
</footer>

dashboard/templates/_main_sidebar.html
{% load adminlte_helpers %}
{%load static %}
<!-- Left side column. contains the sidebar -->
<aside class="main-sidebar sidebar-dark-primary  elevation-4">
     <!-- Brand Logo -->
    {% block logo %}
        <a href="/" class="brand-link">
            <img src="{% static 'images/icon-72x72.png' %}" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
            {% block logo_text %}<span class="brand-text font-weight-light">AdminLTE 3 </span>{% endblock %}
        </a>
    {% endblock %}
    <!-- sidebar: style can be found in sidebar.less -->
    <div class="sidebar">
        <!-- Sidebar user panel (optional) -->
        <div class="user-panel mt-3 pb-3 mb-3 d-flex">
          <div class="image">
            <img src="{% static 'images/icon-72x72.png' %}" class="img-circle elevation-2" alt="User Image">
          </div>
          <div class="info">
            <a href="#" class="d-block">久保直樹</a>
          </div>
        </div>

        <form class="form-inline">
            <div class="input-group">
              <input class="form-control form-control-sidebar" type="search" placeholder="Search" aria-label="Search">
              <div class="input-group-append">
                <button class="btn btn-sidebar" type="submit">
                  <i class="fas fa-search"></i>
                </button>
              </div>
            </div>
        </form>
  
        <!-- Sidebar Menu -->
        <nav class="mt-2">
          <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu">
            <!-- Add icons to the links using the .nav-icon class
                 with font-awesome or any other icon font library -->
            <li class="nav-item has-treeview menu-open">
              <a href="#" class="nav-link active">
                <i class="nav-icon fas fa-tachometer-alt"></i>
                <p>
                  Dashboard
                  <i class="right fas fa-angle-left"></i>
                </p>
              </a>
              <ul class="nav nav-treeview">
                <li class="nav-item">
                  <a href="#" class="nav-link active">
                    <i class="far fa-circle nav-icon"></i>
                    <p>Dashboard 1</p>
                  </a>
                </li>
                <li class="nav-item">
                  <a href="{% url 'dashboard:dashboard2' %}" class="nav-link">
                    <i class="far fa-circle nav-icon"></i>
                    <p>Dashboard 2</p>
                  </a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'dashboard:dashboard3' %}" class="nav-link">
                      <i class="far fa-circle nav-icon"></i>
                      <p>Dashboard 3</p>
                    </a>
                  </li>
              </ul>
            </li>
            <li class="nav-item">
              <a href="#" class="nav-link">
                <i class="nav-icon fas fa-th"></i>
                <p>
                  Simple link
                  <span class="right badge badge-danger">New</span>
                </p>
              </a>
            </li>
          </ul>
        </nav>
        <!-- /.sidebar-menu -->
      </div>
      <!-- /.sidebar -->
</aside>

dashboard/templates/_messages.html
{% if messages %}
    {% for message in messages %}
        {% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
        <div class="alert alert-success alert-dismissible">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            {{ message }}
        </div>
        {% elif message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
        <div class="alert alert-danger alert-dismissible">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            {{ message }}
        </div>
        {% else %}
        <div class="alert alert-info alert-dismissible">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            {{ message }}
        </div>
        {% endif %}
    {% endfor %}
{% endif %}

dashboard/templates/_pagination.html
{% if pager and ROOT_MENU.current_menu.view_name %}
    <ul class="pagination pagination-sm no-margin pull-right">
        <li><a href="{% url ROOT_MENU.current_menu.view_name %}?page=1&{{ pager.url_params }}">&laquo;</a></li>
        {% if pager.page > 2 %}
            <li>
                <a href="{% url ROOT_MENU.current_menu.view_name %}?page={{pager.page|add:-2}}&{{ pager.url_params }}">
                    {{ pager.page | add:-2 }}
                </a>
            </li>
        {% endif %}
        {% if pager.page > 1 %}
            <li>
                <a href="{% url ROOT_MENU.current_menu.view_name %}?page={{pager.page|add:-1}}&{{ pager.url_params }}">
                    {{ pager.page | add:-1 }}
                </a>
            </li>
        {% endif %}
        <li class="active"><a href="#">{{ pager.page }}</a></li>
        {% if pager.has_next %}
            <li>
                <a href="{% url ROOT_MENU.current_menu.view_name %}?page={{pager.page|add:1}}&{{ pager.url_params }}">
                    {{ pager.page | add:1 }}
                </a>
            </li>
        {% endif %}
        {% if pager.has_next_two %}
            <li>
                <a href="{% url ROOT_MENU.current_menu.view_name %}?page={{pager.page|add:2}}&{{ pager.url_params }}">
                    {{ pager.page | add:2 }}
                </a>
            </li>
        {% endif %}
        <li>
            <a href="{% url ROOT_MENU.current_menu.view_name %}?page={{pager.last_page}}&{{ pager.url_params }}">
            &raquo;
            </a>
        </li>
    </ul>
{% endif %}

dashboard/templates/_scripts.html
{% load static %}

{% block scripts %}
<script src="{% static 'admin-lte/plugins/jquery/jquery.min.js' %}"></script>
<script src="{% static 'admin-lte/plugins/jquery-ui/jquery-ui.min.js' %}"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
    $.widget.bridge('uibutton', $.ui.button);
</script>
<script src="{% static 'admin-lte/plugins/bootstrap/js/bootstrap.bundle.min.js' %} "></script>

<!-- ChartJS -->
<script src="{% static 'admin-lte/plugins/chart.js/Chart.min.js' %}"></script>


<script>
    $(function () {
      /* ChartJS
       * -------
       * Here we will create a few charts using ChartJS
       */
  
      //--------------
      //- AREA CHART -
      //--------------
  
      // Get context with jQuery - using jQuery's .get() method.
      var areaChartCanvas = $('#areaChart').get(0).getContext('2d')
  
      var areaChartData = {
        labels  : ['January', 'February', 'March', 'April', 'May', 'June', 'July'],
        datasets: [
          {
            label               : 'Digital Goods',
            backgroundColor     : 'rgba(60,141,188,0.9)',
            borderColor         : 'rgba(60,141,188,0.8)',
            pointRadius          : false,
            pointColor          : '#3b8bba',
            pointStrokeColor    : 'rgba(60,141,188,1)',
            pointHighlightFill  : '#fff',
            pointHighlightStroke: 'rgba(60,141,188,1)',
            data                : [28, 48, 40, 19, 86, 27, 90]
          },
          {
            label               : 'Electronics',
            backgroundColor     : 'rgba(210, 214, 222, 1)',
            borderColor         : 'rgba(210, 214, 222, 1)',
            pointRadius         : false,
            pointColor          : 'rgba(210, 214, 222, 1)',
            pointStrokeColor    : '#c1c7d1',
            pointHighlightFill  : '#fff',
            pointHighlightStroke: 'rgba(220,220,220,1)',
            data                : [65, 59, 80, 81, 56, 55, 40]
          },
        ]
      }
  
      var areaChartOptions = {
        maintainAspectRatio : false,
        responsive : true,
        legend: {
          display: false
        },
        scales: {
          xAxes: [{
            gridLines : {
              display : false,
            }
          }],
          yAxes: [{
            gridLines : {
              display : false,
            }
          }]
        }
      }
  
      // This will get the first returned node in the jQuery collection.
      var areaChart       = new Chart(areaChartCanvas, { 
        type: 'line',
        data: areaChartData, 
        options: areaChartOptions
      })
  
   
    })
  </script>


{% block datatable_js %}{% endblock %}

<script src="{% static 'admin-lte/dist/js/adminlte.min.js' %}"></script>
<script src="{% static 'admin-lte/dist/js/demo.js' %}"></script>
{% endblock %}

dashboard/templates/dashboard2.html
{% load adminlte_helpers i18n %}
{% load static %}
<!DOCTYPE html>
<html>
<head>
    {% block title_outer %}
        <title>{% block title %}Dashboard{% endblock %}</title>
        
        
    {% endblock %}

    {% block meta %}
        <meta charset="utf-8">
        <meta http-equiv="X-UA-COMPATIBLE" content="IE=edge">
        <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    {% endblock %}

    {% block stylesheets %}
        {% include '_styles.html' %}
        {% block style_sheets %}{% endblock %}
    {% endblock %}


{% block extra_head %}
<link rel="icon" href="{% static 'images/favicon.ico' %}">
<link rel="apple-touch-icon" href="{% static 'images/apple-touch-icon-180x180-precomposed.pn' %}">
{% endblock %}

</head>
<body class="hold-transition sidebar-mini {% block body_class %}{% block bodyclass %}layout-fixed {% endblock %}{% endblock %}">

{% block body %}
    <div class="wrapper">
        <!-- Left navbar links -->
        <!-- SEARCH FORM -->
        {% block nav_header %}
            {% include '_main_header.html' %}
        {% endblock %}
        
        <!-- Main Sidebar Container -->
        <!-- Sidebar -->
        <!-- Sidebar Menu -->
        {% block nav_sidebar %}
        {% load adminlte_helpers %}
        {%load static %}
        <!-- Left side column. contains the sidebar -->
        <aside class="main-sidebar sidebar-dark-primary  elevation-4">
             <!-- Brand Logo -->
            {% block logo %}
                <a href="/" class="brand-link">
                    <img src="{% static 'images/icon-72x72.png' %}" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
                    {% block logo_text %}<span class="brand-text font-weight-light">AdminLTE 3 </span>{% endblock %}
                </a>
            {% endblock %}
            <!-- sidebar: style can be found in sidebar.less -->
            <div class="sidebar">
                <!-- Sidebar user panel (optional) -->
                <div class="user-panel mt-3 pb-3 mb-3 d-flex">
                  <div class="image">
                    <img src="{% static 'images/icon-72x72.png' %}" class="img-circle elevation-2" alt="User Image">
                  </div>
                  <div class="info">
                    <a href="#" class="d-block">久保直樹</a>
                  </div>
                </div>
        
                <form class="form-inline">
                    <div class="input-group">
                      <input class="form-control form-control-sidebar" type="search" placeholder="Search" aria-label="Search">
                      <div class="input-group-append">
                        <button class="btn btn-sidebar" type="submit">
                          <i class="fas fa-search"></i>
                        </button>
                      </div>
                    </div>
                </form>
          
                <!-- Sidebar Menu -->
                <nav class="mt-2">
                  <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu">
                    <!-- Add icons to the links using the .nav-icon class
                         with font-awesome or any other icon font library -->
                    <li class="nav-item has-treeview menu-open">
                      <a href="#" class="nav-link active">
                        <i class="nav-icon fas fa-tachometer-alt"></i>
                        <p>
                          Dashboard
                          <i class="right fas fa-angle-left"></i>
                        </p>
                      </a>
                      <ul class="nav nav-treeview">
                        <li class="nav-item">
                          <a href="{% url 'dashboard:main' %}" class="nav-link">
                            <i class="far fa-circle nav-icon"></i>
                            <p>Dashboard 1</p>
                          </a>
                        </li>
                        <li class="nav-item">
                          <a href="{% url 'dashboard:dashboard2' %}" class="nav-link  active">
                            <i class="far fa-circle nav-icon"></i>
                            <p>Dashboard 2</p>
                          </a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'dashboard:dashboard3' %}" class="nav-link">
                              <i class="far fa-circle nav-icon"></i>
                              <p>Dashboard 3</p>
                            </a>
                          </li>
                      </ul>
                    </li>
                    <li class="nav-item">
                      <a href="#" class="nav-link">
                        <i class="nav-icon fas fa-th"></i>
                        <p>
                          Simple link
                          <span class="right badge badge-danger">New</span>
                        </p>
                      </a>
                    </li>
                  </ul>
                </nav>
                <!-- /.sidebar-menu -->
              </div>
              <!-- /.sidebar -->
        </aside>
        
        {% endblock %}

    {% block contents %}
       <!-- Content Wrapper. Contains page content -->
       <!-- Main content -->
   <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0 text-dark">Dashboard 2</h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active">Dashboard 2</li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->


 <!-- Main content -->
 {% block content_outer %}
 <section class="content">
     {% block messages %}
         {% include '_messages.html' %}
     {% endblock %}

     {% block content_block_wrap %}
         {% block content %}
       <!-- ここからメインを書いていく -->
<!-- 引数でviews.pyから引っ張っている -->
<!-- ここから下は棒グラフだが、viewからurlにはひとつしか渡せないので一旦コメントアウトする -->

<canvas id="barChart"></canvas>
<script type="text/javascript">

    // Django viewとの接続方法とsafeの記述
    const ctx = document.getElementById('barChart').getContext('2d');
    const barChart = new Chart(ctx, {
       type: 'bar',
       data: {
           labels: {{ chart_label|safe }},
           datasets: [{
               data: {{ chart_data|safe }},
               backgroundColor: [
                   'rgba(255, 99, 132, 0.2)',
                   'rgba(54, 162, 235, 0.2)',
                   'rgba(255, 206, 86, 0.2)',
                   'rgba(75, 192, 192, 0.2)',
                   'rgba(153, 102, 255, 0.2)',
                   'rgba(255, 159, 64, 0.2)'
               ],
               borderColor: [
                   'rgba(255, 99, 132, 1)',
                   'rgba(54, 162, 235, 1)',
                   'rgba(255, 206, 86, 1)',
                   'rgba(75, 192, 192, 1)',
                   'rgba(153, 102, 255, 1)',
                   'rgba(255, 159, 64, 1)'
               ],
           }]
       },
       options: {
        scales: {
            y: {
                beginAtZero: true
            }
        }
    }
});
  </script> 






         {% endblock %}
     {% endblock %}
 </section>
 {% endblock %}

</div>


    {% endblock %}

        <!-- Control Sidebar -->
        <aside class="control-sidebar control-sidebar-dark">
        <!-- Control sidebar content goes here -->
        <a class="nav-link" data-widget="control-sidebar" href="#">Toggle Control Sidebar</a>
       </aside>
  <!-- /.control-sidebar -->

  <!-- Main Footer -->
        {% block nav_footer %}
            {% include '_main_footer.html' %}
        {% endblock %} 

    </div>
{% endblock body %}
<!-- ./wrapper -->

{% block javascript %}
{% include '_scripts.html' %}
{% block js %}{% endblock %}
{% endblock %}

{% block extra_js %}{% endblock %}

{% block extra_foot %}{% endblock %}
</body>
</html>

dashboard/templates/dashboard3.html
{% load adminlte_helpers i18n %}
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    {% block title_outer %}
        <title>{% block title %}Dashboard{% endblock %}</title>
        
        
    {% endblock %}

    {% block meta %}
        <meta charset="utf-8">
        <meta http-equiv="X-UA-COMPATIBLE" content="IE=edge">
        <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    {% endblock %}

    {% block stylesheets %}
        {% include '_styles.html' %}
        {% block style_sheets %}{% endblock %}
    {% endblock %}


{% block extra_head %}
<link rel="icon" href="{% static 'images/favicon.ico' %}">
<link rel="apple-touch-icon" href="{% static 'images/apple-touch-icon-180x180-precomposed.pn' %}">
{% endblock %}

</head>
<body class="hold-transition sidebar-mini {% block body_class %}{% block bodyclass %}layout-fixed {% endblock %}{% endblock %}">

{% block body %}
    <div class="wrapper">
        <!-- Left navbar links -->
        <!-- SEARCH FORM -->
        {% block nav_header %}
            {% include '_main_header.html' %}
        {% endblock %}
        
        <!-- Main Sidebar Container -->
        <!-- Sidebar -->
        <!-- Sidebar Menu -->
        {% block nav_sidebar %}
        {% load adminlte_helpers %}
        {%load static %}
        <!-- Left side column. contains the sidebar -->
        <aside class="main-sidebar sidebar-dark-primary  elevation-4">
             <!-- Brand Logo -->
            {% block logo %}
                <a href="/" class="brand-link">
                    <img src="{% static 'images/icon-72x72.png' %}" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
                    {% block logo_text %}<span class="brand-text font-weight-light">AdminLTE 3 </span>{% endblock %}
                </a>
            {% endblock %}
            <!-- sidebar: style can be found in sidebar.less -->
            <div class="sidebar">
                <!-- Sidebar user panel (optional) -->
                <div class="user-panel mt-3 pb-3 mb-3 d-flex">
                  <div class="image">
                    <img src="{% static 'images/icon-72x72.png' %}" class="img-circle elevation-2" alt="User Image">
                  </div>
                  <div class="info">
                    <a href="#" class="d-block">久保直樹</a>
                  </div>
                </div>
        
                <form class="form-inline">
                    <div class="input-group">
                      <input class="form-control form-control-sidebar" type="search" placeholder="Search" aria-label="Search">
                      <div class="input-group-append">
                        <button class="btn btn-sidebar" type="submit">
                          <i class="fas fa-search"></i>
                        </button>
                      </div>
                    </div>
                </form>
          
                <!-- Sidebar Menu -->
                <nav class="mt-2">
                  <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu">
                    <!-- Add icons to the links using the .nav-icon class
                         with font-awesome or any other icon font library -->
                    <li class="nav-item has-treeview menu-open">
                      <a href="#" class="nav-link active">
                        <i class="nav-icon fas fa-tachometer-alt"></i>
                        <p>
                          Dashboard
                          <i class="right fas fa-angle-left"></i>
                        </p>
                      </a>
                      <ul class="nav nav-treeview">
                        <li class="nav-item">
                          <a href="{% url 'dashboard:main' %}"  class="nav-link">
                            <i class="far fa-circle nav-icon"></i>
                            <p>Dashboard 1</p>
                          </a>
                        </li>
                        <li class="nav-item">
                          <a href="{% url 'dashboard:dashboard2' %}" class="nav-link">
                            <i class="far fa-circle nav-icon"></i>
                            <p>Dashboard 2</p>
                          </a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'dashboard:dashboard3' %}" class="nav-link active">
                              <i class="far fa-circle nav-icon"></i>
                              <p>Dashboard 3</p>
                            </a>
                          </li>
                      </ul>
                    </li>
                    <li class="nav-item">
                      <a href="#" class="nav-link">
                        <i class="nav-icon fas fa-th"></i>
                        <p>
                          Simple link
                          <span class="right badge badge-danger">New</span>
                        </p>
                      </a>
                    </li>
                  </ul>
                </nav>
                <!-- /.sidebar-menu -->
              </div>
              <!-- /.sidebar -->
        </aside>
        
        {% endblock %}

    {% block contents %}
       <!-- Content Wrapper. Contains page content -->
       <!-- Main content -->
   <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0 text-dark">Dashboard 3</h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active">Dashboard 3</li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->


 <!-- Main content -->
 {% block content_outer %}
 <section class="content">
     {% block messages %}
         {% include '_messages.html' %}
     {% endblock %}

     {% block content_block_wrap %}
         {% block content %}
       <!-- ここからメインを書いていく -->
       
      <!-- matplotlibのグラフ表示 -->
       <img src="data:image/png;base64, {{ graph | safe }} " alt="">


         {% endblock %}
     {% endblock %}
 </section>
 {% endblock %}

</div>


    {% endblock %}

        <!-- Control Sidebar -->
        <aside class="control-sidebar control-sidebar-dark">
        <!-- Control sidebar content goes here -->
        <a class="nav-link" data-widget="control-sidebar" href="#">Toggle Control Sidebar</a>
       </aside>
  <!-- /.control-sidebar -->

  <!-- Main Footer -->
        {% block nav_footer %}
            {% include '_main_footer.html' %}
        {% endblock %} 

    </div>
{% endblock body %}
<!-- ./wrapper -->

{% block javascript %}
{% include '_scripts.html' %}
{% block js %}{% endblock %}
{% endblock %}

{% block extra_js %}{% endblock %}

{% block extra_foot %}{% endblock %}
</body>
</html>

dashboard/templates/main.html
{% extends "base.html" %}
{% load static %}


{% block title %}
Dashboard
{% endblock %}

{% block extra_head %}
<link rel="icon" href="{% static 'images/favicon.ico' %}">
<link rel="apple-touch-icon" href="{% static 'images/apple-touch-icon-180x180-precomposed.pn' %}">
{% endblock %}